import JSZip from "jszip";
import { saveAs } from "file-saver";

export interface BuildFile {
  path: string;
  content: string;
}

export interface BuildResult {
  files: BuildFile[];
}

export async function exportProject(result: BuildResult, projectName: string = "nexus-prime-build") {
  const zip = new JSZip();

  // 1. Add generated files
  result.files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  // 2. Add boilerplate (optional but helpful)
  zip.file("README.md", `# ${projectName}\n\nGenerated by NEXUS PRIME Multi-Agent System.`);
  
  // 3. Generate ZIP
  const content = await zip.generateAsync({ type: "blob" });
  
  // 4. Trigger Download
  saveAs(content, `${projectName}.zip`);
}
