import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/api";
import { z, ZodError } from "zod";

const ExportSchema = z.object({
  userId: z.string().uuid(),
  repoName: z
    .string()
    .min(1)
    .max(100)
    .regex(/^[a-zA-Z0-9._-]+$/),
  files: z.array(
    z.object({
      path: z.string(),
      content: z.string(),
    })
  ),
  isPrivate: z.boolean().default(false),
});

export async function POST(req: Request) {
  try {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const userId = user.id;

    const body = await req.json();
    const { repoName, files, isPrivate } = ExportSchema.parse({ ...body, userId: user.id });

    // Verify user exists
    const { data: profile } = await supabase
      .from("profiles")
      .select("github_token")
      .eq("id", userId)
      .single();

    // Use user's GitHub token if stored, otherwise fall back to app-level
    const ghToken = profile?.github_token || process.env.GITHUB_TOKEN;

    if (!ghToken) {
      return NextResponse.json(
        { error: "GitHub token not configured" },
        { status: 400 }
      );
    }

    // 1. Create repository
    const createRepoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${ghToken}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        private: isPrivate,
        description: "Generated by NEXUS PRIME Multi-Agent System",
        auto_init: true,
      }),
    });

    if (!createRepoRes.ok) {
      const err = await createRepoRes.json();
      if (err.errors?.[0]?.message?.includes("already exists")) {
        return NextResponse.json(
          { error: `Repository '${repoName}' already exists` },
          { status: 409 }
        );
      }
      throw new Error(err.message || "Failed to create repository");
    }

    const repo = await createRepoRes.json();
    const owner = repo.owner.login;

    // 2. Get default branch SHA
    const refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/ref/heads/main`,
      {
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: "application/vnd.github+json",
        },
      }
    );
    const refData = await refRes.json();
    const baseSha = refData.object.sha;

    // 3. Create blobs for each file
    const blobPromises = files.map(async (file) => {
      const blobRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/blobs`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${ghToken}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            content: file.content,
            encoding: "utf-8",
          }),
        }
      );
      const blob = await blobRes.json();
      return { path: file.path, sha: blob.sha, mode: "100644", type: "blob" };
    });

    const blobs = await Promise.all(blobPromises);

    // 4. Create tree
    const treeRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/trees`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          base_tree: baseSha,
          tree: blobs,
        }),
      }
    );
    const tree = await treeRes.json();

    // 5. Create commit
    const commitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/commits`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "feat: Initial build from NEXUS PRIME",
          tree: tree.sha,
          parents: [baseSha],
        }),
      }
    );
    const commit = await commitRes.json();

    // 6. Update ref
    await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`,
      {
        method: "PATCH",
        headers: {
          Authorization: `Bearer ${ghToken}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ sha: commit.sha }),
      }
    );

    return NextResponse.json({
      url: repo.html_url,
      repoFullName: repo.full_name,
      commitSha: commit.sha,
    });
  } catch (error: any) {
    if (error instanceof ZodError) {
      return NextResponse.json(
        { error: "Validation failed", details: error.errors },
        { status: 400 }
      );
    }
    console.error("GitHub Export Error:", error);
    return NextResponse.json(
      { error: error.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}
