"use client";

import React, { useState } from "react";

interface ExportToGitHubProps {
  projectId: string;
  projectName: string;
}

interface ExportConfig {
  repoName: string;
  repoVisibility: "public" | "private";
  description: string;
  branch: string;
  includeEnvExample: boolean;
  includeReadme: boolean;
  includeGitignore: boolean;
  includeCICD: boolean;
  ciProvider: "github-actions" | "vercel" | "none";
  commitMessage: string;
}

interface ExportLog {
  step: string;
  status: "pending" | "running" | "done" | "error";
  detail?: string;
}

export default function ExportToGitHub({ projectId, projectName }: ExportToGitHubProps) {
  const [step, setStep] = useState<"config" | "exporting" | "done">("config");
  const [config, setConfig] = useState<ExportConfig>({
    repoName: projectName?.toLowerCase().replace(/[^a-z0-9-]/g, "-") || "my-nexus-app",
    repoVisibility: "private",
    description: `Generated by Nexus Prime — AI Application Builder`,
    branch: "main",
    includeEnvExample: true,
    includeReadme: true,
    includeGitignore: true,
    includeCICD: true,
    ciProvider: "github-actions",
    commitMessage: "Initial export from Nexus Prime",
  });
  const [logs, setLogs] = useState<ExportLog[]>([]);
  const [repoUrl, setRepoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isGitHubConnected, setIsGitHubConnected] = useState(true);

  const startExport = async () => {
    setStep("exporting");
    setError(null);
    setLogs([
      { step: "Creating repository", status: "running" },
      { step: "Generating project files", status: "pending" },
      { step: "Creating .env.example", status: "pending" },
      { step: "Generating README.md", status: "pending" },
      { step: "Adding CI/CD config", status: "pending" },
      { step: "Pushing to GitHub", status: "pending" },
    ]);

    try {
      const res = await fetch(`/api/projects/${projectId}/export/github`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(config),
      });

      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || "Export failed");
      }

      // Simulate progress via SSE or polling
      const reader = res.body?.getReader();
      const decoder = new TextDecoder();

      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          const chunk = decoder.decode(value);
          const lines = chunk.split("\n").filter(Boolean);

          for (const line of lines) {
            try {
              const update = JSON.parse(line);
              if (update.type === "progress") {
                setLogs((prev) =>
                  prev.map((log, i) =>
                    i === update.step ? { ...log, status: update.status, detail: update.detail } : log
                  )
                );
              } else if (update.type === "complete") {
                setRepoUrl(update.repoUrl);
                setStep("done");
              } else if (update.type === "error") {
                throw new Error(update.message);
              }
            } catch (e) {
              // Skip non-JSON lines
            }
          }
        }
      } else {
        // Fallback: non-streaming response
        const result = await res.json();
        setRepoUrl(result.repoUrl);
        setLogs((prev) => prev.map((l) => ({ ...l, status: "done" })));
        setStep("done");
      }
    } catch (err: any) {
      setError(err.message);
      setLogs((prev) =>
        prev.map((l) => (l.status === "running" ? { ...l, status: "error", detail: err.message } : l))
      );
    }
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", background: "#0a0a0a", color: "#e5e5e5" }}>
      {/* Header */}
      <div style={{ padding: "16px 20px", borderBottom: "1px solid #262626" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="#e5e5e5">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
          </svg>
          <h2 style={{ margin: 0, fontSize: "16px", fontWeight: 600 }}>Export to GitHub</h2>
        </div>
      </div>

      <div style={{ flex: 1, overflow: "auto", padding: "16px 20px" }}>
        {!isGitHubConnected ? (
          <div style={{ textAlign: "center", padding: "60px" }}>
            <div style={{ fontSize: "36px", marginBottom: "12px" }}>🔗</div>
            <p>Connect your GitHub account to export</p>
            <button onClick={() => {
              window.open("https://github.com/login/oauth/authorize", "_blank");
            }} style={{
              padding: "10px 20px", borderRadius: "8px", border: "none",
              background: "#171717", color: "#e5e5e5", cursor: "pointer", fontSize: "14px",
              marginTop: "12px",
            }}>
              Connect GitHub
            </button>
          </div>
        ) : step === "config" ? (
          <div>
            {/* Repository name */}
            <div style={{ marginBottom: "16px" }}>
              <label style={{ display: "block", fontSize: "12px", color: "#a3a3a3", marginBottom: "4px" }}>Repository Name</label>
              <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                <span style={{ fontSize: "13px", color: "#525252" }}>github.com/you/</span>
                <input
                  type="text"
                  value={config.repoName}
                  onChange={(e) => setConfig((prev) => ({ ...prev, repoName: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") }))}
                  style={{
                    flex: 1, padding: "10px 14px", borderRadius: "8px",
                    border: "1px solid #262626", background: "#171717",
                    color: "#e5e5e5", fontSize: "13px", fontFamily: "monospace",
                  }}
                />
              </div>
            </div>

            {/* Visibility */}
            <div style={{ marginBottom: "16px" }}>
              <label style={{ display: "block", fontSize: "12px", color: "#a3a3a3", marginBottom: "8px" }}>Visibility</label>
              <div style={{ display: "flex", gap: "8px" }}>
                {(["private", "public"] as const).map((vis) => (
                  <button
                    key={vis}
                    onClick={() => setConfig((prev) => ({ ...prev, repoVisibility: vis }))}
                    style={{
                      padding: "10px 20px", borderRadius: "8px", border: "1px solid",
                      borderColor: config.repoVisibility === vis ? "#6366f1" : "#262626",
                      background: config.repoVisibility === vis ? "#1e1b4b" : "transparent",
                      color: config.repoVisibility === vis ? "#a5b4fc" : "#737373",
                      cursor: "pointer", fontSize: "13px",
                    }}
                  >
                    {vis === "private" ? "🔒" : "🌐"} {vis.charAt(0).toUpperCase() + vis.slice(1)}
                  </button>
                ))}
              </div>
            </div>

            {/* Description */}
            <div style={{ marginBottom: "16px" }}>
              <label style={{ display: "block", fontSize: "12px", color: "#a3a3a3", marginBottom: "4px" }}>Description</label>
              <input
                type="text"
                value={config.description}
                onChange={(e) => setConfig((prev) => ({ ...prev, description: e.target.value }))}
                style={{
                  width: "100%", padding: "10px 14px", borderRadius: "8px",
                  border: "1px solid #262626", background: "#171717",
                  color: "#e5e5e5", fontSize: "13px", boxSizing: "border-box",
                }}
              />
            </div>

            {/* Include options */}
            <div style={{ marginBottom: "16px" }}>
              <label style={{ display: "block", fontSize: "12px", color: "#a3a3a3", marginBottom: "8px" }}>Include</label>
              <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                {[
                  { key: "includeReadme" as const, label: "README.md", desc: "Auto-generated project documentation with setup instructions", icon: "📄" },
                  { key: "includeEnvExample" as const, label: ".env.example", desc: "Template with required environment variables (no secrets)", icon: "🔐" },
                  { key: "includeGitignore" as const, label: ".gitignore", desc: "Exclude node_modules, .env, build artifacts", icon: "🚫" },
                  { key: "includeCICD" as const, label: "CI/CD Configuration", desc: "Automated build, test, and deploy pipeline", icon: "⚙️" },
                ].map((opt) => (
                  <label key={opt.key} style={{
                    display: "flex", alignItems: "center", gap: "12px",
                    padding: "10px 14px", borderRadius: "8px",
                    background: config[opt.key] ? "#6366f108" : "transparent",
                    border: `1px solid ${config[opt.key] ? "#6366f140" : "#262626"}`,
                    cursor: "pointer",
                  }}>
                    <input
                      type="checkbox"
                      checked={config[opt.key]}
                      onChange={(e) => setConfig((prev) => ({ ...prev, [opt.key]: e.target.checked }))}
                    />
                    <span style={{ fontSize: "16px" }}>{opt.icon}</span>
                    <div>
                      <div style={{ fontSize: "13px", fontWeight: 500 }}>{opt.label}</div>
                      <div style={{ fontSize: "11px", color: "#525252" }}>{opt.desc}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* CI Provider */}
            {config.includeCICD && (
              <div style={{ marginBottom: "16px" }}>
                <label style={{ display: "block", fontSize: "12px", color: "#a3a3a3", marginBottom: "8px" }}>CI/CD Provider</label>
                <div style={{ display: "flex", gap: "8px" }}>
                  {[
                    { id: "github-actions" as const, label: "GitHub Actions", icon: "⚡" },
                    { id: "vercel" as const, label: "Vercel", icon: "▲" },
                  ].map((ci) => (
                    <button
                      key={ci.id}
                      onClick={() => setConfig((prev) => ({ ...prev, ciProvider: ci.id }))}
                      style={{
                        padding: "8px 16px", borderRadius: "8px", border: "1px solid",
                        borderColor: config.ciProvider === ci.id ? "#6366f1" : "#262626",
                        background: config.ciProvider === ci.id ? "#1e1b4b" : "transparent",
                        color: config.ciProvider === ci.id ? "#a5b4fc" : "#737373",
                        cursor: "pointer", fontSize: "12px",
                      }}
                    >
                      {ci.icon} {ci.label}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Commit message */}
            <div style={{ marginBottom: "20px" }}>
              <label style={{ display: "block", fontSize: "12px", color: "#a3a3a3", marginBottom: "4px" }}>Commit Message</label>
              <input
                type="text"
                value={config.commitMessage}
                onChange={(e) => setConfig((prev) => ({ ...prev, commitMessage: e.target.value }))}
                style={{
                  width: "100%", padding: "10px 14px", borderRadius: "8px",
                  border: "1px solid #262626", background: "#171717",
                  color: "#e5e5e5", fontSize: "13px", fontFamily: "monospace", boxSizing: "border-box",
                }}
              />
            </div>

            {/* Export button */}
            <button
              onClick={startExport}
              style={{
                width: "100%", padding: "12px", borderRadius: "10px", border: "none",
                background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                color: "#fff", cursor: "pointer", fontSize: "15px", fontWeight: 700,
              }}
            >
              🚀 Export to GitHub
            </button>
          </div>
        ) : step === "exporting" ? (
          <div>
            <h3 style={{ margin: "0 0 16px", fontSize: "15px" }}>Exporting to GitHub...</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              {logs.map((log, i) => (
                <div key={i} style={{
                  display: "flex", alignItems: "center", gap: "10px",
                  padding: "10px 14px", borderRadius: "8px",
                  background: "#171717", border: "1px solid #262626",
                }}>
                  <span style={{ fontSize: "16px" }}>
                    {log.status === "done" ? "✅" : log.status === "running" ? "⏳" : log.status === "error" ? "❌" : "⬜"}
                  </span>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: "13px", color: log.status === "pending" ? "#3f3f46" : "#e5e5e5" }}>{log.step}</div>
                    {log.detail && <div style={{ fontSize: "11px", color: "#525252" }}>{log.detail}</div>}
                  </div>
                </div>
              ))}
            </div>
            {error && (
              <div style={{
                marginTop: "16px", padding: "12px", borderRadius: "8px",
                background: "#7f1d1d20", border: "1px solid #7f1d1d",
                color: "#ef4444", fontSize: "13px",
              }}>
                ❌ {error}
                <button onClick={startExport} style={{
                  display: "block", marginTop: "8px", padding: "6px 12px", borderRadius: "6px",
                  border: "none", background: "#6366f1", color: "#fff", cursor: "pointer", fontSize: "12px",
                }}>
                  Retry
                </button>
              </div>
            )}
          </div>
        ) : (
          <div style={{ textAlign: "center", padding: "40px" }}>
            <div style={{ fontSize: "48px", marginBottom: "16px" }}>🎉</div>
            <h3 style={{ margin: "0 0 8px", fontSize: "18px" }}>Exported Successfully!</h3>
            <p style={{ color: "#737373", marginBottom: "20px" }}>
              Your project is now on GitHub
            </p>
            {repoUrl && (
              <a
                href={repoUrl}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: "inline-block", padding: "12px 24px", borderRadius: "10px",
                  background: "#171717", color: "#e5e5e5", textDecoration: "none",
                  fontSize: "14px", fontWeight: 600, border: "1px solid #262626",
                }}
              >
                View Repository →
              </a>
            )}
            <div style={{ marginTop: "16px" }}>
              <button
                onClick={() => { setStep("config"); setLogs([]); setRepoUrl(null); }}
                style={{
                  padding: "8px 16px", borderRadius: "8px", border: "1px solid #262626",
                  background: "transparent", color: "#737373", cursor: "pointer", fontSize: "13px",
                }}
              >
                Export Again
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
