import JSZip from "jszip";
import { saveAs } from "file-saver";

export interface BuildFile {
  path: string;
  content: string;
}

export interface BuildResult {
  files: BuildFile[];
}

export type ExportTarget = "zip" | "github" | "netlify" | "cloudflare";

/**
 * Export project as ZIP download
 */
export async function exportProject(
  result: BuildResult,
  projectName: string = "nexus-prime-build"
) {
  const zip = new JSZip();

  result.files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  // Add boilerplate
  zip.file(
    "README.md",
    `# ${projectName}\n\nGenerated by NEXUS PRIME Multi-Agent System.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
  );

  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
        dependencies: {
          next: "14.2.3",
          react: "^18",
          "react-dom": "^18",
          "lucide-react": "^0.330.0",
          tailwindcss: "^3.3.0",
          autoprefixer: "^10.0.1",
          postcss: "^8",
          typescript: "^5",
        },
      },
      null,
      2
    )
  );

  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${projectName}.zip`);
}

/**
 * Push project to a new GitHub repository
 */
export async function exportToGitHub(
  result: BuildResult,
  repoName: string,
  userId: string
): Promise<{ url: string; repoFullName: string }> {
  const response = await fetch("/api/export/github", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      userId,
      repoName,
      files: result.files,
    }),
  });

  const data = await response.json();
  if (!response.ok) throw new Error(data.error || "GitHub export failed");
  return data;
}

/**
 * Deploy to Netlify
 */
export async function exportToNetlify(
  result: BuildResult,
  siteName: string
): Promise<{ url: string; deployId: string }> {
  const response = await fetch("/api/export/netlify", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      siteName,
      files: result.files,
    }),
  });

  const data = await response.json();
  if (!response.ok) throw new Error(data.error || "Netlify deploy failed");
  return data;
}

/**
 * Deploy to Cloudflare Pages
 */
export async function exportToCloudflare(
  result: BuildResult,
  projectName: string
): Promise<{ url: string; deploymentId: string }> {
  const response = await fetch("/api/export/cloudflare", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      projectName,
      files: result.files,
    }),
  });

  const data = await response.json();
  if (!response.ok)
    throw new Error(data.error || "Cloudflare deploy failed");
  return data;
}
